### ISSUE TITLE
Keep on failing installing because of the missing files

### ISSUE THREAD

**Issue by Xuan-1998** [mikeqfu/pydriosm#17]
![image](https://user-images.githubusercontent.com/58761221/141706621-bcbdf944-7b4d-4ddf-9e5e-3e1d86cd55b1.png)
Hi there, I tried both ways the documentatino provided, but it seems doesn't work for me

**Comment by mikeqfu** [comment]
@Xuan-1998 Were you able to install GDAL successfully? Please have a look at the "**Note**" section in [Installation](https://pydriosm.readthedocs.io/en/latest/installation.html). Does the method mentioned there (e.g. try to install [GDAL‑3.3.3‑x.whl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal) first) solve the problem you encountered? If that still doesn't work, please post the full message about the errors raised from running `pip install pydriosm`.
