### ISSUE TITLE
Incompatible with newer releases of pyhelpers

### ISSUE THREAD

**Issue by N3on1x** [mikeqfu/pydriosm#29]
Several modules of the [pyhelpers](https://github.com/mikeqfu/pyhelpers) package has changed names in newer releases, which results in `ModuleNotFoundError`s, e.g. 
```
ModuleNotFoundError: No module named 'pyhelpers.dir'
```

Examples of renamed modules in pyhelpers are:
`dir` --> `dirs`
`sql` --> `dbms`
(There might be more. I have not investigated this thouroghly)

See `pyhelpers` [releases page](https://github.com/mikeqfu/pyhelpers/releases) for more info.

This is a problem for new installs of pydriosm because [`setup.py`](https://github.com/mikeqfu/pydriosm/blob/1003ac6a55cdb6b3f25cc4ed3a7d508419486b55/setup.py#L64) requires `pyhelpers>=1.2.15`.

**Comment by mikeqfu** [comment]
Thanks @N3on1x. The latest version of pydriosm 2.1.0, which relies on pyhelpers>=1.4.3, should resolve the issue.
